routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'verified'],function(){
    Route::get('/profile', 'Frontend\UserController@index')->name('home');
    Route::get('/download-invoice', 'Frontend\UserController@downloadInvoice');

    Route::post('/upload-voucher', 'Frontend\UserController@uploadVoucher');
  
    Route::get('/getfile/{id}/{filename}','Frontend\UserController@getFIle');
    Route::post('/abstract-submission','HomeController@abstractSubmission')->name('abstract-submission');
    Route::get('/apply','HomeController@apply');
    
    Route::get('/esewa-init','Frontend\UserController@esewaInit');
    Route::get('/payment/esewa/esewa_payment/success', 'Frontend\UserController@success')->name('esewa.success');
    Route::get('/payment/esewa/esewa_payment/failure', 'Frontend\UserController@failure')->name('esewa.failure');

});

Route::get('/guidelines','HomeController@guidelines');
Route::get('/abstract-guidelines','HomeController@abstractGuidelines');
Route::get('/poster-guidelines','HomeController@posterGuidelines');
Route::get('/brochure',function(){
    return view('frontend.brochure');
});

Route::get('/committees','HomeController@committees');
Route::get('/immigration','HomeController@immigration');

Route::get('/conference','HomeController@event');
Route::get('/about','HomeController@about');
Route::get('/contact','HomeController@contact');


Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::resource('events','Admin\EventController');
    Route::get('/applications/viewall','Admin\ApplicationController@all')->name('applications.all');
    Route::get('/applications/getfile/{id}/{filename}','Admin\ApplicationController@getfile');

    Route::get('/applications/{id}/accept','Admin\ApplicationController@accept');
    Route::get('/applications/{id}/reject','Admin\ApplicationController@reject');
    Route::resource('applications', 'Admin\ApplicationController');
    Route::get('/participant/{id}/print','Admin\ParticipantController@print');

    Route::resource('participants', 'Admin\ParticipantController');
    Route::get('/payments/{id}/getfile','Admin\PaymentController@getFile');
    Route::get('/payments/{id}/verify','Admin\PaymentController@verify');
    Route::get('/payments/{id}/reject','Admin\PaymentController@reject');

    Route::resource('payments', 'Admin\PaymentController');


    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);



    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('optimize');

app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function event()
    {
        return $this->belongsTo('App\Event');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\UserResetPasswordNotification;
use App\Notifications\UserVerificationNotification;
use App\Payment;
use App\Event;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title','gender','age','phone',
        'email', 'password',
        'first_name',
        'middle_name',
        'last_name',
        'designation',
        'dob',
        'address1',
        'address2',
        'city',
        'country',
        'affiliation',
        'af_address',
        'participant_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    public function getNameAttribute(){
        return $this->title. ' '. $this->first_name . ' ' .$this->middle_name. ' '. $this->last_name;
    }

    public function getAddressAttribute()
    {
        return $this->address1.', '.$this->address2.', '.$this->city.', '.$this->country;
    }
    public function getEducationAttribute()
    {
        return $this->affiliation;
    }
    public function getApplicationAttribute()
    {
        $event_id=Event::latest()->first()->id;
        $applications= Application::where('user_id',$this->id)->where('event_id',$event_id)->get();

        if($applications->count()>0)
            return $applications->first();
        else   
            return NULL;
    }

    public function applications()
    {
        return $this->hasMany('App\Application');
    }
    
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new UserResetPasswordNotification($token));
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new UserVerificationNotification());
    }
    
    public function getPaidStatusAttribute()
    {
        $event_id=Event::latest()->first()->id;
        if(Payment::where('event_id',$event_id)->where('user_id',$this->id)->where('status','!=','Temp')->count()>0)
        {

            return Payment::where('event_id',$event_id)->where('user_id',$this->id)->where('status','!=','Temp')->first()->status;
        }
        else return "unpaid";
    }
}

app/Http/Controllers/Admin/ApplicationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Event;
use App\Application;
use App\Mail\ApplicationStatusMail;
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Session;
use Redirect;
use Mail;

class ApplicationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin_user');
    }

    public function index(Request $request)
    {
        $event_id=Event::latest()->first()->id;

        $applications = [];

        $topic = $request->topic == 'all' ? null : $request->topic;
        $theme = $request->theme == 'all' ? null : $request->theme;

        $query = Application::where('event_id',$event_id)->where('status','submitted')->orderBy('updated_at','desc');

        if($topic){
            $topics = [
                'Health and Medicine',
                'Water and Energy',
                'Food and Agriculture',
                'Transport and Tourism',
                'Information and Communication Technology',
                'Forest and Environment',
                'Disaster Risk Reduction',
                'Indigenous Knowledge and Technology',
                'Fundamental Sciences',
                'Applied Sciences',
                'Emerging Technology',
                'Clean and Green Sciences',
                'Economics and Management',
                'Policy',
                'Philosophy'
            ];
            if($topic == 'Others')
                $query->whereNotIn('topic',$topics);
            else {
                $query->where('topic',$topic);
            }
        }

        if($theme){

            $_applications = $query->get();

            foreach($_applications as $n){
                $themes = json_decode($n->theme);

                if(in_array($theme,$themes)){
                    $applications []= $n;
                }
            }
            $applications = $this->paginate($applications, $perPage = 10, $page = null, $options = ['path' => route('applications.index')]);

        }else{
            $applications = $query->paginate(10);
        }
       
        return view('admin.applications.index')->with('applications',$applications);
    }


    public function all(Request $request)
    {
        $applications = [];

        $topic = $request->topic == 'all' ? null : $request->topic;
        $theme = $request->theme == 'all' ? null : $request->theme;

        $query = Application::orderBy('updated_at','desc');

        if($topic){
            $topics = [
                'Health and Medicine',
                'Water and Energy',
                'Food and Agriculture',
                'Transport and Tourism',
                'Information and Communication Technology',
                'Forest and Environment',
                'Disaster Risk Reduction',
                'Indigenous Knowledge and Technology',
                'Fundamental Sciences',
                'Applied Sciences',
                'Emerging Technology',
                'Clean and Green Sciences',
                'Economics and Management',
                'Policy',
                'Philosophy'
            ];
            if($topic == 'Others')
                $query->whereNotIn('topic',$topics);
            else {
                $query->where('topic',$topic);
            }
        }

        if($theme){

            $_applications = $query->get();

            foreach($_applications as $n){
                $themes = json_decode($n->theme);

                if(in_array($theme,$themes)){
                    $applications []= $n;
                }
            }
            $applications = $this->paginate($applications, $perPage = 10, $page = null, $options = ['path' => route('applications.all')]);

        }else{
            $applications = $query->paginate(10);
        }

        return view('admin.applications.all')->with('applications',$applications);
    }

    public function store(Request $request)
    {
       
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $_applications = Application::findOrFail($id);

        return view('admin.applications.show',compact('_applications'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $_applications = Application::findOrFail($id);

        return view('admin.applications.edit',compact('_applications'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([          
            'title' => 'required|max:191',
            'description' => 'required',
            'application_date' => 'required|date',
            'image' => 'nullable|image'
        ]);

        $_applications = Application::findOrFail($id);
       
        $_applications->title = $request->title;

        $_applications->description = $request->description;

        $_applications->application_date = $request->application_date;
        
        if($request->hasFile('image')){

            if($_applications->image)
                unlink(public_path('application_images/'.$_applications->image));

            $photo = $request->file('image');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            $location = public_path('application_images/');
            $photo->move($location,$filename);
            $_applications->image = $filename;
        }

        $_applications->save();

        $request->session()->flash('success', 'Application updated.');        
        
        return redirect()->route('applications.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $_applications = Application::findOrFail($id);

        if($_applications->image)
            unlink(public_path('application_images/'.$_applications->image));

        $_applications->delete();

        $request->session()->flash('success', 'Application deleted.');        
        
        return redirect()->route('applications.index');
    }

    public function accept($id)
    {
        $_application = Application::findOrFail($id);
        $_application->status="accepted";
        $_application->save();
        Session::flash('success', 'Successfully marked as accpeted.');   

        Mail::send(new ApplicationStatusMail($_application));
        
        return redirect()->route('applications.index');

    }

    public function reject($id)
    {
        $_application = Application::findOrFail($id);
        $_application->status="rejected";
        $_application->save();
        Session::flash('success', 'Successfully marked as rejected.');   

        Mail::send(new ApplicationStatusMail($_application));
        
        return redirect()->route('applications.index');

    }

    public function getFile($id,$filename)
    {
        $_application = Application::findOrFail($id);

        if($_application->status == 'submitted'){
            $_application->status="under review";
            $_application->save();

            Mail::send(new ApplicationStatusMail($_application));
        }

        $filename=$_application->abstract_file;

        try{
            $path = \Storage::get('public/abstract_files/'.$filename);
            $mimetype = \Storage::mimeType('public/abstract_files/'.$filename);

            return \Response::make($path, 200, ['Content-Type' => $mimetype]);
        }
        catch (\Exception $e) {
            abort(404);
        }
    }

    private function paginate($items, $perPage = 15, $page = null, $options = [])
	{
		$page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
		$items = $items instanceof Collection ? $items : Collection::make($items);
		return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
	}
}

resources/views/admin/applications/edit.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Edit Events</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('events.update',$_events->id) }}"  enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PATCH" >

                        <div class="form-body">

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input class="form-control{{ $errors->has('title') ? ' border-danger' : '' }}" id="title" type="text" class="form-control" name="title" value="{{ $_events->title }}" required>

                                        @if ($errors->has('title'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('title') }}</strong>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                                
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Details</label>
                                        @if ($errors->has('description'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('description') }}</strong>
                                            </div>
                                        @endif
                                        <textarea cols="50" rows="20" class="content form-control{{ $errors->has('description') ? ' border-danger' : '' }}" id="en_content" name="description">{{ $_events->description }}</textarea>
                                
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title">Event Date</label>
                                <input class="form-control{{ $errors->has('event_date') ? ' border-danger' : '' }}" id="event_date" type="date" class="form-control" name="event_date" value="{{ $_events->event_date }}" required>

                                @if ($errors->has('event_date'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('event_date') }}</strong>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label>Image</label>
                                <input class="form-control{{ $errors->has('image') ? ' border-danger' : '' }}" type="file" placeholder="Photo"  name="image">

                                @if ($errors->has('image'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </div>
                                @endif
                                <br>
                                <label>Current Image:</label><br>
                                <img style="height:5rem" src="/event_images/{{$_events->image}}" >
                            </div>

                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea.content",
           
           plugins: [
               "advlist autolink lists link charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link",
           toolbar2: "print preview | forecolor backcolor emoticons"
       });
   </script>
  
@endsection

resources/views/admin/applications/show.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Application #{{ $_applications->id }}</h2>
        </div>
        <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
            <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                    <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ url()->previous() }}">Back</a>
                    {{-- <a class="btn btn-warning btn-min-width mr-1 mb-1 " href="{{ route('applications.edit',$_applications->id) }}">Edit</a> --}}
                </ol>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section class="card">
            <div class="card-body collapse in">
                <div class="card-block">
                    <p><b>Name:</b> {{$_applications->user->name}}</p>
                    <p><b>Address:</b> {{$_applications->user->address}} </p>
                    <p><b>Date of Birth:</b> {{$_applications->user->dob}} </p>
                    <p><b>Education:</b> {{$_applications->user->education}} </p>
                    <p><b>Title:</b> {{$_applications->title}} </p>
                    <p><b>Topic:</b> {{$_applications->topic}} </p>
                    <p><b>Themes:</b> @foreach(json_decode($_applications->theme) as $theme){{$theme}} @if(!$loop->last),@endif @endforeach </p>


                    <p><b>Abstract:</b> <a target="_blank" href="/admin/applications/getfile/{{$_applications->id}}/{{$_applications->abstract_file}}">{{$_applications->abstract_file}}</a> </p>
                            (On downloading the file, user will be notified. Status of application will be set to under review)
                    <div class="tab-content px-1 pt-1">
                       
                    </div>

                    {{-- @if($_applications->status != 'accepted' && $_applications->status != 'rejected') --}}
                        <a href="/admin/applications/{{$_applications->id}}/accept" class="btn btn-success">Mark as Accepted</a>
                        <a href="/admin/applications/{{$_applications->id}}/reject" class="btn btn-danger">Mark as Rejected</a>

                    {{-- @endif --}}
                </div>
            </div>
        </section>
    </div>

@endsection